sudo: false
language: node_js
node_js:
  - '12.10.0'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
  - npm run coveralls
deploy:
  local_dir: 'examples/dist'
  provider: pages
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  script:
    - (cd examples && npm run build)
  on:
    branch: master